name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      
      - name: 🏗️ Build
        run: nix build . --accept-flake-config

      - name: 🧪 Test
        run: nix develop .#ci --accept-flake-config --command bash -c "cabal update && cabal test"

      - name: 🎨 Format check
        run: nix fmt --accept-flake-config -- --ci

      - name: 🔍 Lint
        run: nix run .#lint --accept-flake-config

      - name: ❄️ Nix lint
        run: nix develop .#default --accept-flake-config --command just check-nix
